### ISSUE TITLE
[scrum] 200324 화요일 팀 스크럼 

### ISSUE THREAD

**Issue by delmaSong** [codesquad-memeber-2020/signup-5#20]
12시까지 아래의 포맷으로 코멘트 작성해주시면 됩니다 😊
- 어제 한일
- 오늘 계획 
- 본인 컨디션
- 어려웠던 점, 고민했던 것, 느낀 점

**Comment by delmaSong** [comment]
### 어제 한일
- [회원가입] 화면 관련 기능 PR 요청( issue#1)
- [개인정보] 화면 관련 기능 구현 

### 오늘 할 일
- [회원가입] 화면 기능 피드백 반영
- [개인정보] 화면 기능 PR 요청

### 오늘 컨디션
- 눈이 침침해요.. 

### 고민되는 것
- 피드백 받은 사항 중, 델리게이트와 뷰 관련 된 것 중 공통 기능을 분리하는데
거기에 다형성을 어떻게 적용해야할지 무척 고민됩니다.! ..
오늘은 이걸 메인 토픽으로 보내지 않을까 싶어요 🤔

**Comment by moonelysian** [comment]
### 어제한 일
- User 데이터 베이스 구조 설계
- [회원가입] 일단 에러 처리 없이 회원가입 기능 구현

### 오늘 할 일
- [ 로그인 ] 로그인 기능 구현
- [ 배포 ] 헤로쿠로 하다가 자동 빌드가 안되서 일단 멈춤

### 오늘 컨디션
- 좋습니당!

### 고민되는 것
1. 회원가입  Request 시 날짜 형식을  "2020-10-20" 이런 형식으로 지정했는데 잘못된 형식(ex.20201020)으로 왔을 때 에러처리가 쉽지 않을꺼 같아 조금 걱정입니다 :rabbit:

2.  깃이 꼬일 듯한 느낌적인 느낌느낌 :worried:

**Comment by seungdeng17** [comment]
### 어제 한일
- 깃 이슈 정리
- 깃 프로젝트 추가
- 구글 스프레드 시트 작성
- 소스파일 디렉토리
- htmlcss 브랜치 dev pr 후 머지 #14 

### 오늘 계획
- js 파일 세분화
- 입력 된 정보를 json 형태로 만들기

### 오늘 컨디션
- 늦게 자서 피곤한데 집에서 작업해서 괜찮을 것 같습니다

### 고민되는 것
- number type으로 지정한 input elment에 영문 'e'가 입력되는 이슈가 있어요..

**Comment by Hyune-c** [comment]
- 어제한 일
  - DB 스키마 정의
  - AWS 에 테스트 프로젝트 구동

- 오늘 할 일
  - Heroku 를 통한 프로젝트 빌드 #21
  - 

- 오늘 컨디션
  - 양호

- 고민되는 것
  - 없음
