### ISSUE TITLE
[scrum] 200325 

### ISSUE THREAD

**Issue by moonelysian** [codesquad-memeber-2020/signup-5#32]
### 어제 한 일
- 중복 검증 api
- 로그인 기능
- api 문서 다듬기
- mockup 서버 사용하기

### 오늘의 컨디션
- 피곤하다...

### 오늘 할 일
- aws 강의 듣기
- 코드 리팩토링

### 고민거리
- 지금은 이미 꼬인거 같고...다음엔 폴더 만들기 전에 BE 브랜치만 만들어서 거기에 서버 내용만 올려놓고 그 브랜치를 배포하는 방향으로 해야겠당

**Comment by seungdeng17** [comment]
### 어제 한일
- js 세분화
- form 입력 정보 json 만들기

### 오늘 할 일
- 메인 화면 만들기, 로그인 화면 수정
- 아이디, 이메일, 전화번호 중복 검증
- 클라이언트 빌드 강의 듣기

### 컨디션
- 404

### 고민되는 점
- 이거 맞나???

**Comment by Hyune-c** [comment]
- 어제 한일
  - 회원 가입 input 값 검증
  - 회원 가입 구현
  - Heroku 배포 
- 오늘 계획
  - Heroku 배포 
- 본인 컨디션
  - 의욕이 조금 떨어진 상태입니다.
- 어려웠던 점, 고민했던 것, 느낀 점
  - 어떻게 해야될지 좀 막막했는데, Dion 이 만든 자료를 전달 받았으니 그걸 보고 하면 될 것 같습니다.
  - merge 되는 branch 의 관리와 테스트 지원에 대한 생각을 하고 있습니다.

**Comment by Hyune-c** [comment]
- 오늘 계획 추가
  - origin:server/feature/join -> origin:dev PR merge 시키기
  - #30 의 개선 사항 수정
  - origin:dev 의 소스 Heroku 에 배포하기
