### ISSUE TITLE
Whitelabel Error Page 에 대한 처리

### ISSUE THREAD

**Issue by Hyune-c** [codesquad-memeber-2020/signup-5#43]
- [ ] Whitelabel Error Page 에 대한 처리

**Comment by moonelysian** [comment]
이건 무슨 이슈에요??

**Comment by Hyune-c** [comment]
@moonelysian `404 처리`에 대한 내용이 #8 에 있어서 #8 내용을 수정하면서 분리 했습니다.
유효하지 않은 경로로의 접근을 처리하는 것인데 이건 패스 할까요?

**Comment by moonelysian** [comment]
패스해도 될꺼 같아요~
