### ISSUE TITLE
[scrum] 200326

### ISSUE THREAD

**Issue by Hyune-c** [codesquad-memeber-2020/signup-5#46]
- 어제한 일
  - #34 VerifyFormatUtil 개선
    -  fommatting 메소드 안에서 null 체크
  - #34 input 검증 후 회원 가입
    -  boolean isValidUser() 에서 void checkValidUser() 로 메소드 명 변경
  - #35 userValidation 개선
    -  VerifyFormatUtil 의 fommatting 메소드를 사용하지 않는 필드에 대하여 null, "" 체크
  - #35 USER DB constraint 추가
    - UNIQUE KEY 추가 : ID,USER_ID
  - 각 스텝 별 Test 수행
  - #21 Heroku 배포
    - Dev Branch 배포 (https://signup-5-dev.herokuapp.com/)
    - DB 접속 가능하게 설정 (https://signup-5-dev.herokuapp.com/h2-console)
- 오늘 할 일
  - #8 개인정보 조회 
  - #21 master 가 merge 되는 경우 Heroku master 도 올릴 예정 
  - #44 설정 변경 
- 오늘 컨디션
  - 양호
- 고민되는 것
  - 오후 수업과 저녁 약속으로 목표치만큼 할 수 있을지 걱정입니다.

**Comment by moonelysian** [comment]
### 어제 한 일
- 병원가기...ㅜㅜ
- 동아리 착출되기...ㅜㅜ
- 단 코드 확인하기
- aws 강의 듣기

### 오늘 할 일
- aws 강의 마저 듣기
- 수업 듣기
- 프론트 작업한거 넣어보기

### 오늘의 컨디션
- 양호

### 고민되는 것
- 리팩토링...

**Comment by seungdeng17** [comment]
### 어제 한일
- PR 피드백 반영
- 가입정보 데이터 서버로 보내고 응답받기
- 데모 페이지 (테스트 받고 버그 수정..중..)
- 클라이언트 빌드 강의 듣기

### 오늘 할 일
- select input box 맥에서도 같아 보이게 수정
- 로그인, 메인 페이지 만들기
- webpack, babel 적용

### 컨디션
- 좋습니다! 

### 고민되는 점
- 서버에서 해줄 수 있는 것과 클라이언트에서 해야 할 것에 대한 이해가 부족합니다.

**Comment by delmaSong** [comment]
### 어제 한일
- 회원가입 화면 피드백 반영
- 회원정보 화면 PR
- 약관 화면 기능 구현

### 오늘 할 일
- 브랜치 정리
- 관심사 화면 기능 구현
- 야곰 수업 듣기

### 컨디션
- 굿굿

### 고민되는 점
- 앞에꺼 걍 머지하고 뒤에꺼 개발해도 되려나.. 브랜치땜시
